# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    # Test name: search
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://www.baidu.com/")
    # 2 | setWindowSize | 1382x744 |  | 
    self.driver.set_window_size(1382, 744)
    # 3 | type | id=kw | Selenium | 
    self.driver.find_element(By.ID, "kw").send_keys("Selenium")
    # 4 | click | id=su |  | 
    self.driver.find_element(By.ID, "su").click()
  
